export const liftNames: Record<string, string> = {
  squat: 'Squat',
  bench: 'Bench Press',
  deadlift: 'Deadlift',
  ohp: 'Overhead Press',
};

export const liftNamesShort: Record<string, string> = {
  squat: 'Squat',
  bench: 'Benchpress',
  deadlift: 'Deadlift',
  ohp: 'Overhead Press',
};

export const baseExercises = {
  squat: [
    { name: 'Romanian Deadlift', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Bulgarian Split Squats', reps: '8-10', sets: 3, isBodyweight: false },
    { name: 'Leg Curls', reps: '12-15', sets: 3, isBodyweight: false },
    { name: 'Plank', reps: '30-60 sec', sets: 3, isBodyweight: true },
  ],
  bench: [
    { name: 'Incline DB Press', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Barbell Curls', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Tricep Pressdowns', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Face Pulls', reps: '15-20', sets: 3, isBodyweight: false },
  ],
  deadlift: [
    { name: 'Leg Press', reps: '5-8', sets: 3, isBodyweight: false },
    { name: 'B Stance RDLs', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Barbell Rows', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Abs', reps: '10-15 min', sets: 3, isBodyweight: true },
  ],
  ohp: [
    { name: 'Close-Grip Bench', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Lat Pull-Overs', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Lateral Raise Complex', reps: '12-15', sets: 3, isBodyweight: false },
    { name: 'Rear Delt Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  ],
};

export const additionalExercises = [
  { name: 'Box Squats', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Pause Squats', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Front Squats', reps: '6-10', sets: 3, isBodyweight: false },
  { name: 'Goblet Squats', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Walking Lunges', reps: '8-12', sets: 3, isBodyweight: false },
  { name: 'Leg Extensions', reps: '12-15', sets: 3, isBodyweight: false },
  { name: 'Calf Raises', reps: '15-20', sets: 3, isBodyweight: false },
  { name: 'Seated Calf Raises', reps: '15-20', sets: 3, isBodyweight: false },
  { name: 'Hip Thrusts', reps: '8-12', sets: 3, isBodyweight: false },
  { name: 'Hip Abduction', reps: '12-15', sets: 3, isBodyweight: false },
  { name: 'Nordic Curls', reps: '5-8', sets: 3, isBodyweight: true },
  { name: 'Chin-Ups', reps: '6-10', sets: 3, isBodyweight: true },
  { name: 'Pull-Ups', reps: '6-10', sets: 3, isBodyweight: true },
  { name: 'Chest Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Cable Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Shrugs', reps: '12-15', sets: 3, isBodyweight: false },
  { name: 'Farmer Walks', reps: '30-60 sec', sets: 3, isBodyweight: false },
  { name: 'Anderson Squats', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Safety Bar Box Squats', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Tempo Squats', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Pin Squats', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Single-Leg Calf Raises', reps: '12-15', sets: 3, isBodyweight: true },
  { name: 'Donkey Calf Raises', reps: '15-20', sets: 3, isBodyweight: false },
  { name: 'Jump Rope', reps: '60-120 sec', sets: 3, isBodyweight: true },
  { name: 'Lateral Band Walks', reps: '12-15', sets: 3, isBodyweight: true },
  { name: 'Clamshells', reps: '15-20', sets: 3, isBodyweight: true },
  { name: 'Fire Hydrants', reps: '15-20', sets: 3, isBodyweight: true },
  { name: 'Cable Hip Abduction', reps: '12-15', sets: 3, isBodyweight: false },
  { name: 'Sissy Squats', reps: '8-12', sets: 3, isBodyweight: true },
  { name: 'Spanish Squats', reps: '10-15', sets: 3, isBodyweight: true },
  { name: 'Terminal Knee Extensions', reps: '12-15', sets: 3, isBodyweight: true },
  { name: 'Zercher Squats', reps: '6-10', sets: 3, isBodyweight: false },
  { name: 'Safety Bar Squats', reps: '6-10', sets: 3, isBodyweight: false },
  { name: 'High Bar Squats', reps: '6-10', sets: 3, isBodyweight: false },
  { name: 'Bodyweight Squats', reps: '15-20', sets: 3, isBodyweight: true },
  { name: 'Dumbbell Squats', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Kettlebell Squats', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Static Lunges', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Reverse Lunges', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Step-Ups', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Leg Press Calf Raises', reps: '15-20', sets: 3, isBodyweight: false },
  { name: 'Single-Leg Seated Calf Raises', reps: '12-15', sets: 3, isBodyweight: false },
  { name: 'Tibialis Raises', reps: '15-20', sets: 3, isBodyweight: true },
  { name: 'Glute Bridges', reps: '12-15', sets: 3, isBodyweight: true },
  { name: 'Single-Leg Hip Thrusts', reps: '8-12', sets: 3, isBodyweight: true },
  { name: 'Cable Pull-Throughs', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Kettlebell Swings', reps: '12-15', sets: 3, isBodyweight: false },
  { name: 'Eccentric Leg Curls', reps: '8-12', sets: 3, isBodyweight: false },
  { name: 'Partner Hamstring Curls', reps: '8-12', sets: 3, isBodyweight: true },
  { name: 'Glute Ham Raise', reps: '6-10', sets: 3, isBodyweight: true },
  { name: 'Slider Hamstring Curls', reps: '10-15', sets: 3, isBodyweight: true },
  { name: 'Assisted Chin-Ups', reps: '8-12', sets: 3, isBodyweight: true },
  { name: 'Underhand Lat Pulldowns', reps: '8-12', sets: 3, isBodyweight: false },
  { name: 'Weighted Chin-Ups', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Lat Pulldowns', reps: '8-12', sets: 3, isBodyweight: false },
  { name: 'Neutral Grip Pull-Ups', reps: '6-10', sets: 3, isBodyweight: true },
  { name: 'Weighted Pull-Ups', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Pec Deck Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Push-Up Plus', reps: '10-15', sets: 3, isBodyweight: true },
  { name: 'Dumbbell Press', reps: '8-12', sets: 3, isBodyweight: false },
  { name: 'Dumbbell Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Resistance Band Flyes', reps: '12-15', sets: 3, isBodyweight: true },
  { name: 'Low-to-High Cable Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'High-to-Low Cable Flyes', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Overhead Shrugs', reps: '10-15', sets: 3, isBodyweight: false },
  { name: 'Rack Pulls', reps: '5-8', sets: 3, isBodyweight: false },
  { name: 'Suitcase Carry', reps: '30-60 sec', sets: 3, isBodyweight: false },
  { name: 'Overhead Carry', reps: '30-60 sec', sets: 3, isBodyweight: false },
  { name: 'Rack Position Carry', reps: '30-60 sec', sets: 3, isBodyweight: false },
];

export const bbbExercises = {
  squat: [
    { name: 'Bulgarian Split Squats', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Abs', reps: '10-15', sets: 3, isBodyweight: true },
  ],
  bench: [
    { name: 'Barbell Rows', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Face Pulls', reps: '15-20', sets: 3, isBodyweight: false },
  ],
  deadlift: [
    { name: 'B Stance RDLs', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Abs', reps: '10-15', sets: 3, isBodyweight: true },
  ],
  ohp: [
    { name: 'Pull-Ups', reps: '6-10', sets: 3, isBodyweight: true },
    { name: 'Lateral Raise Complex', reps: '12-15', sets: 3, isBodyweight: false },
  ],
};

export const bbsExercises = {
  squat: [
    { name: 'Bulgarian Split Squats', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Abs', reps: '10-15', sets: 3, isBodyweight: true },
  ],
  bench: [
    { name: 'Barbell Rows', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Face Pulls', reps: '15-20', sets: 3, isBodyweight: false },
  ],
  deadlift: [
    { name: 'B Stance RDLs', reps: '8-12', sets: 3, isBodyweight: false },
    { name: 'Abs', reps: '10-15', sets: 3, isBodyweight: true },
  ],
  ohp: [
    { name: 'Pull-Ups', reps: '6-10', sets: 3, isBodyweight: true },
    { name: 'Lateral Raise Complex', reps: '12-15', sets: 3, isBodyweight: false },
  ],
};
